export const ActionTypes = {
    SET_WEATHER: 'SET_WEATHER',
    SET_FORECAST_LIST: 'SET_FORECAST_LIST',

    SET_ANIMATION_AUTO_PLAY: 'SET_ANIMATION_AUTO_PLAY',
    SET_IMAGE_SCALE: 'SET_IMAGE_SCALE',
    SET_IMAGE_OPACITY: 'SET_IMAGE_OPACITY',
    SET_IMAGE_BORDER_RADIUS: 'SET_IMAGE_BORDER_RADIUS',
    SET_IMAGE_TRANSLATE_X: 'SET_IMAGE_TRANSLATE_X',
};
